# coding: utf-8

"""
    Squac API

    API for accessing squac data  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.write_only_threshold_serializer import WriteOnlyThresholdSerializer  # noqa: E501
from swagger_client.rest import ApiException


class TestWriteOnlyThresholdSerializer(unittest.TestCase):
    """WriteOnlyThresholdSerializer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWriteOnlyThresholdSerializer(self):
        """Test WriteOnlyThresholdSerializer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.write_only_threshold_serializer.WriteOnlyThresholdSerializer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
