"""
    Squac API

    API for accessing squac data  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import squacapi_client
from squacapi_client.model.read_only_matching_rule_serializer import ReadOnlyMatchingRuleSerializer


class TestReadOnlyMatchingRuleSerializer(unittest.TestCase):
    """ReadOnlyMatchingRuleSerializer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReadOnlyMatchingRuleSerializer(self):
        """Test ReadOnlyMatchingRuleSerializer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReadOnlyMatchingRuleSerializer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
