"""
    Squac API

    API for accessing squac data  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import squacapi_client
from squacapi_client.model.read_only_network_serializer import ReadOnlyNetworkSerializer
globals()['ReadOnlyNetworkSerializer'] = ReadOnlyNetworkSerializer
from squacapi_client.model.v10_nslc_networks_list200_response import V10NslcNetworksList200Response


class TestV10NslcNetworksList200Response(unittest.TestCase):
    """V10NslcNetworksList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV10NslcNetworksList200Response(self):
        """Test V10NslcNetworksList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V10NslcNetworksList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
