# coding: utf-8

"""
    Squac API

    API for accessing squac data  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import squacapi_client
from squacapi_client.models.read_only_organization_serializer import ReadOnlyOrganizationSerializer  # noqa: E501
from squacapi_client.rest import ApiException


class TestReadOnlyOrganizationSerializer(unittest.TestCase):
    """ReadOnlyOrganizationSerializer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReadOnlyOrganizationSerializer(self):
        """Test ReadOnlyOrganizationSerializer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = squacapi_client.models.read_only_organization_serializer.ReadOnlyOrganizationSerializer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
