# coding: utf-8

"""
    Squac API

    API for accessing squac data  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.read_only_dashboard_detail_serializer import ReadOnlyDashboardDetailSerializer  # noqa: E501
from swagger_client.rest import ApiException


class TestReadOnlyDashboardDetailSerializer(unittest.TestCase):
    """ReadOnlyDashboardDetailSerializer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReadOnlyDashboardDetailSerializer(self):
        """Test ReadOnlyDashboardDetailSerializer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.read_only_dashboard_detail_serializer.ReadOnlyDashboardDetailSerializer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
