"""
    Squac API

    API for accessing squac data  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import squacapi_client
from squacapi_client.model.read_only_alert_detail_serializer import ReadOnlyAlertDetailSerializer
globals()['ReadOnlyAlertDetailSerializer'] = ReadOnlyAlertDetailSerializer
from squacapi_client.model.v10_measurement_alerts_list200_response import V10MeasurementAlertsList200Response


class TestV10MeasurementAlertsList200Response(unittest.TestCase):
    """V10MeasurementAlertsList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV10MeasurementAlertsList200Response(self):
        """Test V10MeasurementAlertsList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V10MeasurementAlertsList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
