# coding: utf-8

"""
    Squac API

    API for accessing squac data  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import squacapi_client
from squacapi_client.models.write_only_network_serializer import WriteOnlyNetworkSerializer  # noqa: E501
from squacapi_client.rest import ApiException


class TestWriteOnlyNetworkSerializer(unittest.TestCase):
    """WriteOnlyNetworkSerializer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWriteOnlyNetworkSerializer(self):
        """Test WriteOnlyNetworkSerializer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = squacapi_client.models.write_only_network_serializer.WriteOnlyNetworkSerializer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
