# coding: utf-8

"""
    Squac API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.widget import Widget  # noqa: E501
from swagger_client.rest import ApiException


class TestWidget(unittest.TestCase):
    """Widget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWidget(self):
        """Test Widget"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.widget.Widget()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
