# coding: utf-8

"""
    Squac API

    API for accessing squac data  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import squacapi_client
from squacapi_client.models.write_only_widget_serializer import WriteOnlyWidgetSerializer  # noqa: E501
from squacapi_client.rest import ApiException


class TestWriteOnlyWidgetSerializer(unittest.TestCase):
    """WriteOnlyWidgetSerializer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWriteOnlyWidgetSerializer(self):
        """Test WriteOnlyWidgetSerializer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = squacapi_client.models.write_only_widget_serializer.WriteOnlyWidgetSerializer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
