"""
    Squac API

    API for accessing squac data  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import squacapi_client
from squacapi_client.model.read_only_archive_hour_serializer import ReadOnlyArchiveHourSerializer
globals()['ReadOnlyArchiveHourSerializer'] = ReadOnlyArchiveHourSerializer
from squacapi_client.model.v10_measurement_hour_archives_list200_response import V10MeasurementHourArchivesList200Response


class TestV10MeasurementHourArchivesList200Response(unittest.TestCase):
    """V10MeasurementHourArchivesList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV10MeasurementHourArchivesList200Response(self):
        """Test V10MeasurementHourArchivesList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V10MeasurementHourArchivesList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
