# coding: utf-8

"""
    Squac API

    API for accessing squac data  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import squacapi_client
from squacapi_client.models.read_only_user_write_serializer import ReadOnlyUserWriteSerializer  # noqa: E501
from squacapi_client.rest import ApiException


class TestReadOnlyUserWriteSerializer(unittest.TestCase):
    """ReadOnlyUserWriteSerializer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReadOnlyUserWriteSerializer(self):
        """Test ReadOnlyUserWriteSerializer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = squacapi_client.models.read_only_user_write_serializer.ReadOnlyUserWriteSerializer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
