"""
    Squac API

    API for accessing squac data  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: contact@snippets.local
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import squacapi_client
from squacapi_client.model.read_only_metric_serializer import ReadOnlyMetricSerializer
globals()['ReadOnlyMetricSerializer'] = ReadOnlyMetricSerializer
from squacapi_client.model.v10_measurement_metrics_list200_response import V10MeasurementMetricsList200Response


class TestV10MeasurementMetricsList200Response(unittest.TestCase):
    """V10MeasurementMetricsList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV10MeasurementMetricsList200Response(self):
        """Test V10MeasurementMetricsList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V10MeasurementMetricsList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
