# coding: utf-8

"""
    Squac API

    API for accessing squac data  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.write_only_dashboard_serializer import WriteOnlyDashboardSerializer  # noqa: E501
from swagger_client.rest import ApiException


class TestWriteOnlyDashboardSerializer(unittest.TestCase):
    """WriteOnlyDashboardSerializer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWriteOnlyDashboardSerializer(self):
        """Test WriteOnlyDashboardSerializer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.write_only_dashboard_serializer.WriteOnlyDashboardSerializer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
