# coding: utf-8

# flake8: noqa
"""
    Squac API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.archive import Archive
from swagger_client.models.channel import Channel
from swagger_client.models.dashboard import Dashboard
from swagger_client.models.dashboard_detail import DashboardDetail
from swagger_client.models.email import Email
from swagger_client.models.group import Group
from swagger_client.models.group_detail import GroupDetail
from swagger_client.models.measurement import Measurement
from swagger_client.models.metric import Metric
from swagger_client.models.network import Network
from swagger_client.models.nslc_group import NslcGroup
from swagger_client.models.password_token import PasswordToken
from swagger_client.models.stat_type import StatType
from swagger_client.models.threshold import Threshold
from swagger_client.models.token import Token
from swagger_client.models.user import User
from swagger_client.models.widget import Widget
from swagger_client.models.widget_detail import WidgetDetail
from swagger_client.models.widget_type import WidgetType
