# coding: utf-8

"""
    Squac API

    API for accessing squac data  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Channel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'class_name': 'str',
        'code': 'str',
        'name': 'str',
        'station_code': 'str',
        'station_name': 'str',
        'description': 'str',
        'sample_rate': 'float',
        'network': 'str',
        'loc': 'str',
        'lat': 'float',
        'lon': 'float',
        'elev': 'float',
        'azimuth': 'float',
        'dip': 'float',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'user': 'int',
        'starttime': 'datetime',
        'endtime': 'datetime',
        'nslc': 'str'
    }

    attribute_map = {
        'id': 'id',
        'class_name': 'class_name',
        'code': 'code',
        'name': 'name',
        'station_code': 'station_code',
        'station_name': 'station_name',
        'description': 'description',
        'sample_rate': 'sample_rate',
        'network': 'network',
        'loc': 'loc',
        'lat': 'lat',
        'lon': 'lon',
        'elev': 'elev',
        'azimuth': 'azimuth',
        'dip': 'dip',
        'created_at': 'created_at',
        'updated_at': 'updated_at',
        'user': 'user',
        'starttime': 'starttime',
        'endtime': 'endtime',
        'nslc': 'nslc'
    }

    def __init__(self, id=None, class_name=None, code=None, name=None, station_code=None, station_name=None, description=None, sample_rate=None, network=None, loc='--', lat=None, lon=None, elev=None, azimuth=None, dip=None, created_at=None, updated_at=None, user=None, starttime=None, endtime=None, nslc=None):  # noqa: E501
        """Channel - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._class_name = None
        self._code = None
        self._name = None
        self._station_code = None
        self._station_name = None
        self._description = None
        self._sample_rate = None
        self._network = None
        self._loc = None
        self._lat = None
        self._lon = None
        self._elev = None
        self._azimuth = None
        self._dip = None
        self._created_at = None
        self._updated_at = None
        self._user = None
        self._starttime = None
        self._endtime = None
        self._nslc = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if class_name is not None:
            self.class_name = class_name
        self.code = code
        if name is not None:
            self.name = name
        self.station_code = station_code
        if station_name is not None:
            self.station_name = station_name
        if description is not None:
            self.description = description
        if sample_rate is not None:
            self.sample_rate = sample_rate
        self.network = network
        if loc is not None:
            self.loc = loc
        self.lat = lat
        self.lon = lon
        self.elev = elev
        if azimuth is not None:
            self.azimuth = azimuth
        if dip is not None:
            self.dip = dip
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        if user is not None:
            self.user = user
        if starttime is not None:
            self.starttime = starttime
        if endtime is not None:
            self.endtime = endtime
        if nslc is not None:
            self.nslc = nslc

    @property
    def id(self):
        """Gets the id of this Channel.  # noqa: E501


        :return: The id of this Channel.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Channel.


        :param id: The id of this Channel.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def class_name(self):
        """Gets the class_name of this Channel.  # noqa: E501


        :return: The class_name of this Channel.  # noqa: E501
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name):
        """Sets the class_name of this Channel.


        :param class_name: The class_name of this Channel.  # noqa: E501
        :type: str
        """

        self._class_name = class_name

    @property
    def code(self):
        """Gets the code of this Channel.  # noqa: E501


        :return: The code of this Channel.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this Channel.


        :param code: The code of this Channel.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def name(self):
        """Gets the name of this Channel.  # noqa: E501


        :return: The name of this Channel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Channel.


        :param name: The name of this Channel.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def station_code(self):
        """Gets the station_code of this Channel.  # noqa: E501


        :return: The station_code of this Channel.  # noqa: E501
        :rtype: str
        """
        return self._station_code

    @station_code.setter
    def station_code(self, station_code):
        """Sets the station_code of this Channel.


        :param station_code: The station_code of this Channel.  # noqa: E501
        :type: str
        """
        if station_code is None:
            raise ValueError("Invalid value for `station_code`, must not be `None`")  # noqa: E501

        self._station_code = station_code

    @property
    def station_name(self):
        """Gets the station_name of this Channel.  # noqa: E501


        :return: The station_name of this Channel.  # noqa: E501
        :rtype: str
        """
        return self._station_name

    @station_name.setter
    def station_name(self, station_name):
        """Sets the station_name of this Channel.


        :param station_name: The station_name of this Channel.  # noqa: E501
        :type: str
        """

        self._station_name = station_name

    @property
    def description(self):
        """Gets the description of this Channel.  # noqa: E501


        :return: The description of this Channel.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Channel.


        :param description: The description of this Channel.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def sample_rate(self):
        """Gets the sample_rate of this Channel.  # noqa: E501


        :return: The sample_rate of this Channel.  # noqa: E501
        :rtype: float
        """
        return self._sample_rate

    @sample_rate.setter
    def sample_rate(self, sample_rate):
        """Sets the sample_rate of this Channel.


        :param sample_rate: The sample_rate of this Channel.  # noqa: E501
        :type: float
        """

        self._sample_rate = sample_rate

    @property
    def network(self):
        """Gets the network of this Channel.  # noqa: E501


        :return: The network of this Channel.  # noqa: E501
        :rtype: str
        """
        return self._network

    @network.setter
    def network(self, network):
        """Sets the network of this Channel.


        :param network: The network of this Channel.  # noqa: E501
        :type: str
        """
        if network is None:
            raise ValueError("Invalid value for `network`, must not be `None`")  # noqa: E501

        self._network = network

    @property
    def loc(self):
        """Gets the loc of this Channel.  # noqa: E501


        :return: The loc of this Channel.  # noqa: E501
        :rtype: str
        """
        return self._loc

    @loc.setter
    def loc(self, loc):
        """Sets the loc of this Channel.


        :param loc: The loc of this Channel.  # noqa: E501
        :type: str
        """

        self._loc = loc

    @property
    def lat(self):
        """Gets the lat of this Channel.  # noqa: E501


        :return: The lat of this Channel.  # noqa: E501
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat):
        """Sets the lat of this Channel.


        :param lat: The lat of this Channel.  # noqa: E501
        :type: float
        """
        if lat is None:
            raise ValueError("Invalid value for `lat`, must not be `None`")  # noqa: E501

        self._lat = lat

    @property
    def lon(self):
        """Gets the lon of this Channel.  # noqa: E501


        :return: The lon of this Channel.  # noqa: E501
        :rtype: float
        """
        return self._lon

    @lon.setter
    def lon(self, lon):
        """Sets the lon of this Channel.


        :param lon: The lon of this Channel.  # noqa: E501
        :type: float
        """
        if lon is None:
            raise ValueError("Invalid value for `lon`, must not be `None`")  # noqa: E501

        self._lon = lon

    @property
    def elev(self):
        """Gets the elev of this Channel.  # noqa: E501


        :return: The elev of this Channel.  # noqa: E501
        :rtype: float
        """
        return self._elev

    @elev.setter
    def elev(self, elev):
        """Sets the elev of this Channel.


        :param elev: The elev of this Channel.  # noqa: E501
        :type: float
        """
        if elev is None:
            raise ValueError("Invalid value for `elev`, must not be `None`")  # noqa: E501

        self._elev = elev

    @property
    def azimuth(self):
        """Gets the azimuth of this Channel.  # noqa: E501


        :return: The azimuth of this Channel.  # noqa: E501
        :rtype: float
        """
        return self._azimuth

    @azimuth.setter
    def azimuth(self, azimuth):
        """Sets the azimuth of this Channel.


        :param azimuth: The azimuth of this Channel.  # noqa: E501
        :type: float
        """

        self._azimuth = azimuth

    @property
    def dip(self):
        """Gets the dip of this Channel.  # noqa: E501


        :return: The dip of this Channel.  # noqa: E501
        :rtype: float
        """
        return self._dip

    @dip.setter
    def dip(self, dip):
        """Sets the dip of this Channel.


        :param dip: The dip of this Channel.  # noqa: E501
        :type: float
        """

        self._dip = dip

    @property
    def created_at(self):
        """Gets the created_at of this Channel.  # noqa: E501


        :return: The created_at of this Channel.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Channel.


        :param created_at: The created_at of this Channel.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this Channel.  # noqa: E501


        :return: The updated_at of this Channel.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this Channel.


        :param updated_at: The updated_at of this Channel.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def user(self):
        """Gets the user of this Channel.  # noqa: E501


        :return: The user of this Channel.  # noqa: E501
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this Channel.


        :param user: The user of this Channel.  # noqa: E501
        :type: int
        """

        self._user = user

    @property
    def starttime(self):
        """Gets the starttime of this Channel.  # noqa: E501


        :return: The starttime of this Channel.  # noqa: E501
        :rtype: datetime
        """
        return self._starttime

    @starttime.setter
    def starttime(self, starttime):
        """Sets the starttime of this Channel.


        :param starttime: The starttime of this Channel.  # noqa: E501
        :type: datetime
        """

        self._starttime = starttime

    @property
    def endtime(self):
        """Gets the endtime of this Channel.  # noqa: E501


        :return: The endtime of this Channel.  # noqa: E501
        :rtype: datetime
        """
        return self._endtime

    @endtime.setter
    def endtime(self, endtime):
        """Sets the endtime of this Channel.


        :param endtime: The endtime of this Channel.  # noqa: E501
        :type: datetime
        """

        self._endtime = endtime

    @property
    def nslc(self):
        """Gets the nslc of this Channel.  # noqa: E501


        :return: The nslc of this Channel.  # noqa: E501
        :rtype: str
        """
        return self._nslc

    @nslc.setter
    def nslc(self, nslc):
        """Sets the nslc of this Channel.


        :param nslc: The nslc of this Channel.  # noqa: E501
        :type: str
        """

        self._nslc = nslc

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Channel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Channel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
