# coding: utf-8

"""
    Squac API

    API for accessing squac data  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ReadOnlyMatchingRuleSerializer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'network_regex': 'str',
        'station_regex': 'str',
        'location_regex': 'str',
        'channel_regex': 'str',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'user': 'int',
        'group': 'int',
        'is_include': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'network_regex': 'network_regex',
        'station_regex': 'station_regex',
        'location_regex': 'location_regex',
        'channel_regex': 'channel_regex',
        'created_at': 'created_at',
        'updated_at': 'updated_at',
        'user': 'user',
        'group': 'group',
        'is_include': 'is_include'
    }

    def __init__(self, id=None, network_regex=None, station_regex=None, location_regex=None, channel_regex=None, created_at=None, updated_at=None, user=None, group=None, is_include=None):  # noqa: E501
        """ReadOnlyMatchingRuleSerializer - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._network_regex = None
        self._station_regex = None
        self._location_regex = None
        self._channel_regex = None
        self._created_at = None
        self._updated_at = None
        self._user = None
        self._group = None
        self._is_include = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if network_regex is not None:
            self.network_regex = network_regex
        if station_regex is not None:
            self.station_regex = station_regex
        if location_regex is not None:
            self.location_regex = location_regex
        if channel_regex is not None:
            self.channel_regex = channel_regex
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        if user is not None:
            self.user = user
        self.group = group
        if is_include is not None:
            self.is_include = is_include

    @property
    def id(self):
        """Gets the id of this ReadOnlyMatchingRuleSerializer.  # noqa: E501


        :return: The id of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ReadOnlyMatchingRuleSerializer.


        :param id: The id of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def network_regex(self):
        """Gets the network_regex of this ReadOnlyMatchingRuleSerializer.  # noqa: E501


        :return: The network_regex of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :rtype: str
        """
        return self._network_regex

    @network_regex.setter
    def network_regex(self, network_regex):
        """Sets the network_regex of this ReadOnlyMatchingRuleSerializer.


        :param network_regex: The network_regex of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :type: str
        """

        self._network_regex = network_regex

    @property
    def station_regex(self):
        """Gets the station_regex of this ReadOnlyMatchingRuleSerializer.  # noqa: E501


        :return: The station_regex of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :rtype: str
        """
        return self._station_regex

    @station_regex.setter
    def station_regex(self, station_regex):
        """Sets the station_regex of this ReadOnlyMatchingRuleSerializer.


        :param station_regex: The station_regex of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :type: str
        """

        self._station_regex = station_regex

    @property
    def location_regex(self):
        """Gets the location_regex of this ReadOnlyMatchingRuleSerializer.  # noqa: E501


        :return: The location_regex of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :rtype: str
        """
        return self._location_regex

    @location_regex.setter
    def location_regex(self, location_regex):
        """Sets the location_regex of this ReadOnlyMatchingRuleSerializer.


        :param location_regex: The location_regex of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :type: str
        """

        self._location_regex = location_regex

    @property
    def channel_regex(self):
        """Gets the channel_regex of this ReadOnlyMatchingRuleSerializer.  # noqa: E501


        :return: The channel_regex of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :rtype: str
        """
        return self._channel_regex

    @channel_regex.setter
    def channel_regex(self, channel_regex):
        """Sets the channel_regex of this ReadOnlyMatchingRuleSerializer.


        :param channel_regex: The channel_regex of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :type: str
        """

        self._channel_regex = channel_regex

    @property
    def created_at(self):
        """Gets the created_at of this ReadOnlyMatchingRuleSerializer.  # noqa: E501


        :return: The created_at of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ReadOnlyMatchingRuleSerializer.


        :param created_at: The created_at of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this ReadOnlyMatchingRuleSerializer.  # noqa: E501


        :return: The updated_at of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ReadOnlyMatchingRuleSerializer.


        :param updated_at: The updated_at of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def user(self):
        """Gets the user of this ReadOnlyMatchingRuleSerializer.  # noqa: E501


        :return: The user of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this ReadOnlyMatchingRuleSerializer.


        :param user: The user of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :type: int
        """

        self._user = user

    @property
    def group(self):
        """Gets the group of this ReadOnlyMatchingRuleSerializer.  # noqa: E501


        :return: The group of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :rtype: int
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this ReadOnlyMatchingRuleSerializer.


        :param group: The group of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :type: int
        """
        if group is None:
            raise ValueError("Invalid value for `group`, must not be `None`")  # noqa: E501

        self._group = group

    @property
    def is_include(self):
        """Gets the is_include of this ReadOnlyMatchingRuleSerializer.  # noqa: E501


        :return: The is_include of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :rtype: bool
        """
        return self._is_include

    @is_include.setter
    def is_include(self, is_include):
        """Sets the is_include of this ReadOnlyMatchingRuleSerializer.


        :param is_include: The is_include of this ReadOnlyMatchingRuleSerializer.  # noqa: E501
        :type: bool
        """

        self._is_include = is_include

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReadOnlyMatchingRuleSerializer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReadOnlyMatchingRuleSerializer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
