# coding: utf-8

"""
    Squac API

    API for accessing squac data  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ReadOnlyWidgetSerializer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'dashboard': 'int',
        'metrics': 'list[int]',
        'user': 'int',
        'layout': 'str',
        'type': 'str',
        'properties': 'str',
        'stat': 'str',
        'thresholds': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'dashboard': 'dashboard',
        'metrics': 'metrics',
        'user': 'user',
        'layout': 'layout',
        'type': 'type',
        'properties': 'properties',
        'stat': 'stat',
        'thresholds': 'thresholds'
    }

    def __init__(self, id=None, name=None, dashboard=None, metrics=None, user=None, layout=None, type=None, properties=None, stat=None, thresholds=None):  # noqa: E501
        """ReadOnlyWidgetSerializer - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._dashboard = None
        self._metrics = None
        self._user = None
        self._layout = None
        self._type = None
        self._properties = None
        self._stat = None
        self._thresholds = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.name = name
        self.dashboard = dashboard
        self.metrics = metrics
        if user is not None:
            self.user = user
        if layout is not None:
            self.layout = layout
        if type is not None:
            self.type = type
        if properties is not None:
            self.properties = properties
        if stat is not None:
            self.stat = stat
        if thresholds is not None:
            self.thresholds = thresholds

    @property
    def id(self):
        """Gets the id of this ReadOnlyWidgetSerializer.  # noqa: E501


        :return: The id of this ReadOnlyWidgetSerializer.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ReadOnlyWidgetSerializer.


        :param id: The id of this ReadOnlyWidgetSerializer.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ReadOnlyWidgetSerializer.  # noqa: E501


        :return: The name of this ReadOnlyWidgetSerializer.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ReadOnlyWidgetSerializer.


        :param name: The name of this ReadOnlyWidgetSerializer.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def dashboard(self):
        """Gets the dashboard of this ReadOnlyWidgetSerializer.  # noqa: E501


        :return: The dashboard of this ReadOnlyWidgetSerializer.  # noqa: E501
        :rtype: int
        """
        return self._dashboard

    @dashboard.setter
    def dashboard(self, dashboard):
        """Sets the dashboard of this ReadOnlyWidgetSerializer.


        :param dashboard: The dashboard of this ReadOnlyWidgetSerializer.  # noqa: E501
        :type: int
        """
        if dashboard is None:
            raise ValueError("Invalid value for `dashboard`, must not be `None`")  # noqa: E501

        self._dashboard = dashboard

    @property
    def metrics(self):
        """Gets the metrics of this ReadOnlyWidgetSerializer.  # noqa: E501


        :return: The metrics of this ReadOnlyWidgetSerializer.  # noqa: E501
        :rtype: list[int]
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics):
        """Sets the metrics of this ReadOnlyWidgetSerializer.


        :param metrics: The metrics of this ReadOnlyWidgetSerializer.  # noqa: E501
        :type: list[int]
        """
        if metrics is None:
            raise ValueError("Invalid value for `metrics`, must not be `None`")  # noqa: E501

        self._metrics = metrics

    @property
    def user(self):
        """Gets the user of this ReadOnlyWidgetSerializer.  # noqa: E501


        :return: The user of this ReadOnlyWidgetSerializer.  # noqa: E501
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this ReadOnlyWidgetSerializer.


        :param user: The user of this ReadOnlyWidgetSerializer.  # noqa: E501
        :type: int
        """

        self._user = user

    @property
    def layout(self):
        """Gets the layout of this ReadOnlyWidgetSerializer.  # noqa: E501


        :return: The layout of this ReadOnlyWidgetSerializer.  # noqa: E501
        :rtype: str
        """
        return self._layout

    @layout.setter
    def layout(self, layout):
        """Sets the layout of this ReadOnlyWidgetSerializer.


        :param layout: The layout of this ReadOnlyWidgetSerializer.  # noqa: E501
        :type: str
        """

        self._layout = layout

    @property
    def type(self):
        """Gets the type of this ReadOnlyWidgetSerializer.  # noqa: E501


        :return: The type of this ReadOnlyWidgetSerializer.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ReadOnlyWidgetSerializer.


        :param type: The type of this ReadOnlyWidgetSerializer.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def properties(self):
        """Gets the properties of this ReadOnlyWidgetSerializer.  # noqa: E501


        :return: The properties of this ReadOnlyWidgetSerializer.  # noqa: E501
        :rtype: str
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this ReadOnlyWidgetSerializer.


        :param properties: The properties of this ReadOnlyWidgetSerializer.  # noqa: E501
        :type: str
        """

        self._properties = properties

    @property
    def stat(self):
        """Gets the stat of this ReadOnlyWidgetSerializer.  # noqa: E501


        :return: The stat of this ReadOnlyWidgetSerializer.  # noqa: E501
        :rtype: str
        """
        return self._stat

    @stat.setter
    def stat(self, stat):
        """Sets the stat of this ReadOnlyWidgetSerializer.


        :param stat: The stat of this ReadOnlyWidgetSerializer.  # noqa: E501
        :type: str
        """

        self._stat = stat

    @property
    def thresholds(self):
        """Gets the thresholds of this ReadOnlyWidgetSerializer.  # noqa: E501


        :return: The thresholds of this ReadOnlyWidgetSerializer.  # noqa: E501
        :rtype: str
        """
        return self._thresholds

    @thresholds.setter
    def thresholds(self, thresholds):
        """Sets the thresholds of this ReadOnlyWidgetSerializer.


        :param thresholds: The thresholds of this ReadOnlyWidgetSerializer.  # noqa: E501
        :type: str
        """

        self._thresholds = thresholds

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReadOnlyWidgetSerializer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReadOnlyWidgetSerializer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
