# coding: utf-8

"""
    Squac API

    API for accessing squac data  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from squacapi_client.configuration import Configuration


class ReadOnlyNotificationSerializer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'url': 'str',
        'notification_type': 'str',
        'contact': 'int',
        'level': 'int',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'user_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'url': 'url',
        'notification_type': 'notification_type',
        'contact': 'contact',
        'level': 'level',
        'created_at': 'created_at',
        'updated_at': 'updated_at',
        'user_id': 'user_id'
    }

    def __init__(self, id=None, url=None, notification_type=None, contact=None, level=None, created_at=None, updated_at=None, user_id=None, _configuration=None):  # noqa: E501
        """ReadOnlyNotificationSerializer - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._url = None
        self._notification_type = None
        self._contact = None
        self._level = None
        self._created_at = None
        self._updated_at = None
        self._user_id = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if url is not None:
            self.url = url
        if notification_type is not None:
            self.notification_type = notification_type
        self.contact = contact
        if level is not None:
            self.level = level
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        if user_id is not None:
            self.user_id = user_id

    @property
    def id(self):
        """Gets the id of this ReadOnlyNotificationSerializer.  # noqa: E501


        :return: The id of this ReadOnlyNotificationSerializer.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ReadOnlyNotificationSerializer.


        :param id: The id of this ReadOnlyNotificationSerializer.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def url(self):
        """Gets the url of this ReadOnlyNotificationSerializer.  # noqa: E501


        :return: The url of this ReadOnlyNotificationSerializer.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ReadOnlyNotificationSerializer.


        :param url: The url of this ReadOnlyNotificationSerializer.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def notification_type(self):
        """Gets the notification_type of this ReadOnlyNotificationSerializer.  # noqa: E501


        :return: The notification_type of this ReadOnlyNotificationSerializer.  # noqa: E501
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type):
        """Sets the notification_type of this ReadOnlyNotificationSerializer.


        :param notification_type: The notification_type of this ReadOnlyNotificationSerializer.  # noqa: E501
        :type: str
        """
        allowed_values = ["email", "sms", "slack"]  # noqa: E501
        if (self._configuration.client_side_validation and
                notification_type not in allowed_values):
            raise ValueError(
                "Invalid value for `notification_type` ({0}), must be one of {1}"  # noqa: E501
                .format(notification_type, allowed_values)
            )

        self._notification_type = notification_type

    @property
    def contact(self):
        """Gets the contact of this ReadOnlyNotificationSerializer.  # noqa: E501


        :return: The contact of this ReadOnlyNotificationSerializer.  # noqa: E501
        :rtype: int
        """
        return self._contact

    @contact.setter
    def contact(self, contact):
        """Sets the contact of this ReadOnlyNotificationSerializer.


        :param contact: The contact of this ReadOnlyNotificationSerializer.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and contact is None:
            raise ValueError("Invalid value for `contact`, must not be `None`")  # noqa: E501

        self._contact = contact

    @property
    def level(self):
        """Gets the level of this ReadOnlyNotificationSerializer.  # noqa: E501


        :return: The level of this ReadOnlyNotificationSerializer.  # noqa: E501
        :rtype: int
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this ReadOnlyNotificationSerializer.


        :param level: The level of this ReadOnlyNotificationSerializer.  # noqa: E501
        :type: int
        """

        self._level = level

    @property
    def created_at(self):
        """Gets the created_at of this ReadOnlyNotificationSerializer.  # noqa: E501


        :return: The created_at of this ReadOnlyNotificationSerializer.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ReadOnlyNotificationSerializer.


        :param created_at: The created_at of this ReadOnlyNotificationSerializer.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this ReadOnlyNotificationSerializer.  # noqa: E501


        :return: The updated_at of this ReadOnlyNotificationSerializer.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ReadOnlyNotificationSerializer.


        :param updated_at: The updated_at of this ReadOnlyNotificationSerializer.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def user_id(self):
        """Gets the user_id of this ReadOnlyNotificationSerializer.  # noqa: E501


        :return: The user_id of this ReadOnlyNotificationSerializer.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this ReadOnlyNotificationSerializer.


        :param user_id: The user_id of this ReadOnlyNotificationSerializer.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReadOnlyNotificationSerializer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReadOnlyNotificationSerializer):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ReadOnlyNotificationSerializer):
            return True

        return self.to_dict() != other.to_dict()
