# coding: utf-8

"""
    Squac API

    API for accessing squac data  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WriteOnlyTriggerUnsubscribeSerializer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email': 'str',
        'unsubscribe_all': 'bool'
    }

    attribute_map = {
        'email': 'email',
        'unsubscribe_all': 'unsubscribe_all'
    }

    def __init__(self, email=None, unsubscribe_all=False):  # noqa: E501
        """WriteOnlyTriggerUnsubscribeSerializer - a model defined in Swagger"""  # noqa: E501
        self._email = None
        self._unsubscribe_all = None
        self.discriminator = None
        self.email = email
        if unsubscribe_all is not None:
            self.unsubscribe_all = unsubscribe_all

    @property
    def email(self):
        """Gets the email of this WriteOnlyTriggerUnsubscribeSerializer.  # noqa: E501


        :return: The email of this WriteOnlyTriggerUnsubscribeSerializer.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this WriteOnlyTriggerUnsubscribeSerializer.


        :param email: The email of this WriteOnlyTriggerUnsubscribeSerializer.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def unsubscribe_all(self):
        """Gets the unsubscribe_all of this WriteOnlyTriggerUnsubscribeSerializer.  # noqa: E501

        This will remove you from all email             notifications for this monitor.  # noqa: E501

        :return: The unsubscribe_all of this WriteOnlyTriggerUnsubscribeSerializer.  # noqa: E501
        :rtype: bool
        """
        return self._unsubscribe_all

    @unsubscribe_all.setter
    def unsubscribe_all(self, unsubscribe_all):
        """Sets the unsubscribe_all of this WriteOnlyTriggerUnsubscribeSerializer.

        This will remove you from all email             notifications for this monitor.  # noqa: E501

        :param unsubscribe_all: The unsubscribe_all of this WriteOnlyTriggerUnsubscribeSerializer.  # noqa: E501
        :type: bool
        """

        self._unsubscribe_all = unsubscribe_all

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WriteOnlyTriggerUnsubscribeSerializer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WriteOnlyTriggerUnsubscribeSerializer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
