# coding: utf-8

"""
    Squac API

    API for accessing squac data  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from squacapi_client.configuration import Configuration


class WriteOnlyMeasurementSerializer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'metric': 'int',
        'channel': 'int',
        'value': 'float',
        'starttime': 'datetime',
        'endtime': 'datetime'
    }

    attribute_map = {
        'metric': 'metric',
        'channel': 'channel',
        'value': 'value',
        'starttime': 'starttime',
        'endtime': 'endtime'
    }

    def __init__(self, metric=None, channel=None, value=None, starttime=None, endtime=None, _configuration=None):  # noqa: E501
        """WriteOnlyMeasurementSerializer - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._metric = None
        self._channel = None
        self._value = None
        self._starttime = None
        self._endtime = None
        self.discriminator = None

        self.metric = metric
        self.channel = channel
        self.value = value
        self.starttime = starttime
        self.endtime = endtime

    @property
    def metric(self):
        """Gets the metric of this WriteOnlyMeasurementSerializer.  # noqa: E501


        :return: The metric of this WriteOnlyMeasurementSerializer.  # noqa: E501
        :rtype: int
        """
        return self._metric

    @metric.setter
    def metric(self, metric):
        """Sets the metric of this WriteOnlyMeasurementSerializer.


        :param metric: The metric of this WriteOnlyMeasurementSerializer.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and metric is None:
            raise ValueError("Invalid value for `metric`, must not be `None`")  # noqa: E501

        self._metric = metric

    @property
    def channel(self):
        """Gets the channel of this WriteOnlyMeasurementSerializer.  # noqa: E501


        :return: The channel of this WriteOnlyMeasurementSerializer.  # noqa: E501
        :rtype: int
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this WriteOnlyMeasurementSerializer.


        :param channel: The channel of this WriteOnlyMeasurementSerializer.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and channel is None:
            raise ValueError("Invalid value for `channel`, must not be `None`")  # noqa: E501

        self._channel = channel

    @property
    def value(self):
        """Gets the value of this WriteOnlyMeasurementSerializer.  # noqa: E501


        :return: The value of this WriteOnlyMeasurementSerializer.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this WriteOnlyMeasurementSerializer.


        :param value: The value of this WriteOnlyMeasurementSerializer.  # noqa: E501
        :type: float
        """
        if self._configuration.client_side_validation and value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def starttime(self):
        """Gets the starttime of this WriteOnlyMeasurementSerializer.  # noqa: E501


        :return: The starttime of this WriteOnlyMeasurementSerializer.  # noqa: E501
        :rtype: datetime
        """
        return self._starttime

    @starttime.setter
    def starttime(self, starttime):
        """Sets the starttime of this WriteOnlyMeasurementSerializer.


        :param starttime: The starttime of this WriteOnlyMeasurementSerializer.  # noqa: E501
        :type: datetime
        """
        if self._configuration.client_side_validation and starttime is None:
            raise ValueError("Invalid value for `starttime`, must not be `None`")  # noqa: E501

        self._starttime = starttime

    @property
    def endtime(self):
        """Gets the endtime of this WriteOnlyMeasurementSerializer.  # noqa: E501


        :return: The endtime of this WriteOnlyMeasurementSerializer.  # noqa: E501
        :rtype: datetime
        """
        return self._endtime

    @endtime.setter
    def endtime(self, endtime):
        """Sets the endtime of this WriteOnlyMeasurementSerializer.


        :param endtime: The endtime of this WriteOnlyMeasurementSerializer.  # noqa: E501
        :type: datetime
        """
        if self._configuration.client_side_validation and endtime is None:
            raise ValueError("Invalid value for `endtime`, must not be `None`")  # noqa: E501

        self._endtime = endtime

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WriteOnlyMeasurementSerializer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WriteOnlyMeasurementSerializer):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WriteOnlyMeasurementSerializer):
            return True

        return self.to_dict() != other.to_dict()
